//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wbs.Everdigm.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wbs.Everdigm.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=GBK&quot; /&gt;
        ///    &lt;title&gt;Exception&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body
        ///        {
        ///            font: 75% Verdana, Arial, helvetica, sans-serif;
        ///            color: #000;
        ///            background: #FFFFFF;
        ///        }
        ///
        ///        .content
        ///        {
        ///            color: #505050;
        ///            margin: 0 auto;
        ///            w [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mail_content {
            get {
                return ResourceManager.GetString("mail_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;code&quot;:&quot;000000&quot;,&quot;data&quot;:{&quot;totalPages&quot;:4,&quot;pageSize&quot;:10,&quot;total&quot;:37,&quot;pageNumber&quot;:1,&quot;list&quot;:[{&quot;name&quot;:&quot;测试啦&quot;,&quot;id&quot;:&quot;58ba5a4037db4820dcb67c7f&quot;,&quot;content&quot;:&quot;我是测试内容&quot;,&quot;serNum&quot;:21},{&quot;name&quot;:&quot;测试啦&quot;,&quot;id&quot;:&quot;58ba5a4d37db4820dcb67c80&quot;,&quot;content&quot;:&quot;我是测试内容&quot;,&quot;serNum&quot;:21},{&quot;name&quot;:&quot;测试啦&quot;,&quot;id&quot;:&quot;58ba5a4d37db4820dcb67c81&quot;,&quot;content&quot;:&quot;我是测试内容&quot;,&quot;serNum&quot;:21},{&quot;name&quot;:&quot;测试啦&quot;,&quot;id&quot;:&quot;58ba5a4d37db4820dcb67c82&quot;,&quot;content&quot;:&quot;我是测试内容&quot;,&quot;serNum&quot;:21},{&quot;name&quot;:&quot;测试啦&quot;,&quot;id&quot;:&quot;58ba5a4e37db4820dcb67c83&quot;,&quot;content&quot;:&quot;我是测试内容&quot;,&quot;serNum&quot;:21},{&quot;name&quot;:&quot;测试啦&quot;,&quot;id&quot;:&quot;58ba5a4e37db48 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string testQueryJson {
            get {
                return ResourceManager.GetString("testQueryJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;code&quot;:&quot;000000&quot;,&quot;data&quot;:{&quot;_id&quot;:&quot;123456&quot;,&quot;name&quot;:&quot;test&quot;,&quot;loginId&quot;:&quot;1234&quot;,&quot;phone&quot;:&quot;13999999999&quot;,&quot;email&quot;:&quot;asdf@asdf.com&quot;,&quot;password&quot;:&quot;123456&quot;,&quot;createDate&quot;:&quot;2017-04-15 20:30:28&quot;}} 的本地化字符串。
        /// </summary>
        internal static string testSingleJson {
            get {
                return ResourceManager.GetString("testSingleJson", resourceCulture);
            }
        }
    }
}
